#!/bin/sh
REMOTE_PATTERN=${1:-".+"}

git config -l | \
  egrep "remote\.$REMOTE_PATTERN\.url" | \
  sed -E "s/^.+\=//" | \
  sed -E 's/git@github\.com:(.+)\.git/https:\/\/github.com\/\1/' | \
  sed -E 's/https:\/\/github\.com\/(.+)\.git/https:\/\/github.com\/\1/' | \
  sed -E 's/git@[^\.]+\.git\.beanstalkapp\.com:\/([^\/]+)\/([^\.]+)\.git/https:\/\/\1.beanstalkapp.com\/\2/' | \
  sed -E 's/git@[^\.]+\.beanstalkapp\.com:\/([^\/]+)\/([^\.]+)\.git/https:\/\/\1.beanstalkapp.com\/\2/' | \
  egrep '^https://.+'
